AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - beta
      - gamma
      - prod
    Default: beta
    Description: Stage that can be added to resource names

Resources:
  TripApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: app/
      Runtime: nodejs4.3
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEventSource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  TripData:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: tripId
      Type: String
    SortKey:
      Name: ts
      Type: Number

  Trips:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: userId
      Type: String
    SortKey:
      Name: tripId
      Type: String

Outputs:
  ApiUrl:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: !Sub 'ApiUrl-${Stage}'
